<map version="1.0.1">
<node TEXT="Learning R">
<node TEXT="序言（一） "></node>
<node TEXT="序言（二） "></node>
<node TEXT="前言：思 R 不学则殆 ">
<node TEXT="R的学习困境 "></node>
<node TEXT="R是什么  "></node></node>
<node TEXT="初见 ">
<node TEXT="结缘：下载安装 "></node>
<node TEXT="第一次畅谈：计算 "></node>
<node TEXT="第一张留影：作图 "></node>
<node TEXT="课外活动：表白"></node></node>
<node TEXT="数据 ">
<node TEXT="输入：读取文件 "></node>
<node TEXT="计算：数据处理和作图 "></node>
<node TEXT="输出：保存文件 "></node>
<node TEXT="课外活动：有R伴我走天涯  "></node></node>
<node TEXT="作图 ">
<node TEXT="控制图像：线型，点状，颜色 "></node>
<node TEXT="丰富内容：直线，网格，图例 "></node>
<node TEXT="多图合一：三种布局 "></node>
<node TEXT="保存图片：pdf，png，jpg "></node>
<node TEXT="课外活动： R的毛坯房与精装修 "></node></node>
<node TEXT="拟合 ">
<node TEXT="线性拟合：散点图的趋势线 "></node>
<node TEXT="在绘图区添加数学表达式 "></node>
<node TEXT="非线性拟合：一个指数递减模型 "></node>
<node TEXT="课外活动：助理团与自助餐 "></node></node>
<node TEXT="循环 ">
<node TEXT="假如没有循环  "></node>
<node TEXT="循环是个救世主 "></node>
<node TEXT="人口增长模型  "></node>
<node TEXT="制作动画 "></node>
<node TEXT="超越循环 "></node>
<node TEXT="课外活动：信息提示 "></node></node>
<node TEXT="分支 ">
<node TEXT="判断：逻辑运算 "></node>
<node TEXT="选择：如果，那么，否则  "></node>
<node TEXT="课外活动：复活节"></node></node>
<node TEXT="办公 ">
<node TEXT="从Excel到R代码 "></node>
<node TEXT="从Word到R文档 "></node>
<node TEXT="从Powerpoint到R幻灯片 "></node>
<node TEXT="课外活动：丰富多彩的幻灯片 "></node></node>
<node TEXT="习题 ">
<node TEXT="向量、矩阵、数据框和列表 "></node>
<node TEXT="A卷：照猫画虎题  "></node>
<node TEXT="B卷：自由发挥题 "></node></node>
<node TEXT="函数 ">
<node TEXT="内置函数：全自动厨师机 "></node>
<node TEXT="自定义函数：自制厨师机 "></node>
<node TEXT="扩展包：美食王国 "></node>
<node TEXT="包的开发：开疆拓土 "></node>
<node TEXT="课外活动：餐后甜点 "></node></node>
<node TEXT="字符 ">
<node TEXT="狐狸从懒狗身上跳过 "></node>
<node TEXT="千字文的重复字 "></node>
<node TEXT="整理读书笔记"></node>
<node TEXT="课外活动：张无忌的困惑 "></node></node>
<node TEXT="地图 ">
<node TEXT="绘制点阵地图 "></node>
<node TEXT="绘制矢量地图 "></node>
<node TEXT="绘制交互地图 "></node>
<node TEXT="课外活动：绘制动画地图 "></node></node>
<node TEXT="时间 ">
<node TEXT="时刻数据的获取 "></node>
<node TEXT="时刻数据的格式 "></node>
<node TEXT="时刻数据的计算 "></node>
<node TEXT="时刻的作图 "></node>
<node TEXT="课外活动：夏令时 "></node></node>
<node TEXT="批量处理文件 ">
<node TEXT="批量整理照片文件 "></node>
<node TEXT="从网页批量下载和整理图片 "></node>
<node TEXT="从大量文件里提取汇总信息 "></node>
<node TEXT="课外活动：打通任督二脉 "></node></node>
<node TEXT="论文书稿写作 ">
<node TEXT="魅力不可挡"></node>
<node TEXT="准备工作 "></node>
<node TEXT="见证奇迹的时刻 "></node>
<node TEXT="撰写学术论文 "></node>
<node TEXT="撰写学位论文 "></node>
<node TEXT="生成思维导图 "></node>
<node TEXT="撰写散文和日记 "></node>
<node TEXT="记录吉他谱 "></node>
<node TEXT="课外活动：创建新模板 "></node></node>
<node TEXT="搭建小型网站 ">
<node TEXT="准备工作 "></node>
<node TEXT="搭建个人博客 "></node>
<node TEXT="搭建科研网站 "></node>
<node TEXT="课外活动：搭建自己的网站 "></node></node>
<node TEXT="在工作中应用 ">
<node TEXT="自动完成业务报表 "></node>
<node TEXT="可重复性研究报告"></node>
<node TEXT="课外活动：学以致用 "></node></node>
<node TEXT="用 R 进行基础统计（一）：概率分布检验 ">
<node TEXT="统计检验的基本思想"></node>
<node TEXT="离散型随机变量和连续型随机变量 "></node>
<node TEXT="二项分布 "></node>
<node TEXT="泊松分布 "></node>
<node TEXT="卡方分布 "></node>
<node TEXT="正态分布 "></node>
<node TEXT="指数分布 "></node>
<node TEXT="伽马分布 "></node>
<node TEXT="韦伯分布 "></node>
<node TEXT="检验两个向量是否来自同一分布 "></node>
<node TEXT="课外活动：概率函数汇总 "></node></node>
<node TEXT="用 R 进行基础统计（二）：均值比较和方差分析 ">
<node TEXT="单正态总体的检验 "></node>
<node TEXT="双正态总体的检验 "></node>
<node TEXT="配对 *t* 检验 "></node>
<node TEXT="多组之间均值比较：多组样本的配对 *t* 检验 "></node>
<node TEXT="方差分析 ">
<node TEXT="单因素方差分析 "></node>
<node TEXT="不考虑交互作用的双因素方差分析 "></node>
<node TEXT="考虑交互作用的双因素方差分析 "></node></node>
<node TEXT="非参数假设检验 ">
<node TEXT="单样本检验 "></node>
<node TEXT="两独立样本秩检验 "></node>
<node TEXT="Mann-Whitney U检验 "></node>
<node TEXT="多个独立样本的秩和检验 "></node>
<node TEXT="多个相关样本的秩和检验 "></node></node></node>
<node TEXT="相关性分析和协方差 ">
<node TEXT="相关性检验及可视化 "></node>
<node TEXT="协方差 "></node></node>
<node TEXT="后记：学 R 时习之 "></node>
<node TEXT="附录">
<node TEXT="Markdown 和 bookdown 语法速查 "></node>
<node TEXT="答疑 ">
<node TEXT="菜鸟常犯错误和常见问题 "></node>
<node TEXT="习题参考答案 "></node></node></node>
</node></map>
