---
title: '有那么几回，我也想跳楼：写给我的中年朋友们'
author: "赵鹏"
date: '2017-12-20'
slug: midlife-pressure
summary: "你渣，自有人更渣，他们都不跳楼，你跳什么？"
tags:
  - post
  - blog
---

1

中兴员工跳楼，让人唏嘘叹惋。有人说是因为行业衰落，有人抱怨程序员压力太大。在我看来，这些纯属借题发挥。在不了解现场详细过程的情况下，人们怎么就那么确定是这些原因呢？当事人年岁已过不惑，阅历丰富，儿女双全，有两套房，与其说是因为经济压力而突然跳楼，我还不如相信这是一个意外，比如死者以跳楼来威胁对方答应条件时不慎坠落，或者是受抑郁症驱使而一时失控等等——当事人已经不在了，真相谁会知道呢？

不过，死者遭遇的中年危机是事实。同样是中年人，同样是失业在即，同样是家有俩娃要还房贷，既然说起这个话题，我也借题发挥，谈谈我对自杀一事的看法。为死者讳，事后去妄加揣度这个中年人的工作、家庭和心理状态是极为不妥的，因此我下面所写的，都跟这个悲剧的当事人没有任何关系，只是由这个事件引发而已。因为，回顾自己这半辈子，有那么几回，我也想跳楼。

2

一路走来，回头去看，你有没有动过轻生的念头，哪怕只有一点点？

当年刚离开故乡，只身远赴千里之外的大学校园，没过多久，我就不想活了。

从上小学起，我的学习成绩傲视群雄，在五线小城里独孤求败；到了京城的大学一看，高手如云，上课一个字都听不懂，考试及格是奇迹，顿时学霸成学渣。

现在回头去看，这点破事儿算什么。完全是因为一路顺风顺水，不懂什么叫挫折，一时心里落差太大而造成的不适而已。但是回到当时，如果有点什么小事刺激一下，鬼使神差爬上楼顶……这种事时不时在校园里发生，只不过跳的不是我；我躲过此劫的原因之一，就是跟着同样沦为学渣的兄弟们混。你渣，自有人更渣，他们都不跳楼，你跳什么？

咬牙念完大学，混迹于滚滚红尘的江湖里，我觉得活着没啥奔头了。

江湖好混乱，人性太复杂。有人可以不劳而获坐享其成，有人却是累死累活还得背黑锅；微薄的薪水捉襟见肘地养着房贷和日渐成长的娃，往未来去看，看不到光明。

好在那时心境已经比读书时宽了许多，知道跟人攀比是没有尽头的。要是真攀比，谁活得长谁赢。于是，开始接受那些能接受的，改变那些能改变的。既不能接受又不能改变，那就选择躲开。

后来出国读书，熬博士论文期间，觉得生不如死。

在那个阶段里，天天过得暗无天日，真心觉得挺不下去了，还不如把这个学位放弃一死了之。

几年后的一天，已经距离博士毕业两年有余，遇见当年一起读博的韩国哥们儿，他抱着我想哭，后来一边喝酒一边谈笑。他花了 8 年，在我毕业之后一年多才干完。回忆当年一起在野外做观测的点点滴滴，觉得日子过得厚重。

跟中年人所承受的压力相比，回望这些经历，无非是青少年时期学业和事业里的小菜一碟，属于无病呻吟，为赋新词强说愁。那么，等到老年，回望中年的经历，会不会也觉得淡如云烟呢？

前提是得活到老年那一天。

3

有个老同学在朋友圈里分享了一篇文章，标题是“你失踪了，会惊动谁”。我留言说：会惊动房东和银行。我每个月得交房租，得还国内的房贷。

二十多岁，两手空空，拿累了就放下；三十来岁，左手拿累了就交给右手；四十多岁，双手都拎着东西，累了只能左右换一下。

中年人面对的考验，更多，更凶险。

我看到关于跳楼事件的一些言论，都是归罪于行业衰落和个人经济压力。如果是这样，那就给自杀找来了合理性，只怕将来会让更多人走上轻生的不归路。生活的压力不是什么新鲜事。如果不是衔着金汤匙出生，那么草根生活原本不就是这么累吗？

科幻小说《三体》里，外星文明即将对人类实施灭绝计划之前，对人类这样说：

> 生存本来就是一种幸运，过去的地球上是如此，现在这个冷酷的宇宙中也到处如此。但不知从什么时候起，人类有了一种幻觉，认为生存成了唾手可得的东西，这就是你们失败的根本原因。

从什么时候起，我们开始有了这种幻觉，觉得生存是件唾手可得的东西，而忘记生存本身的艰难呢？

记得以前同事里有个大姐，比我大十来岁，有一次听我抱怨，就说：

> 你们这些年轻人，不知足，年纪轻轻就自己租房买房了。我们这一代人，结婚了也一直跟父母一起住一辈子，哪里有条件去租房买房，想都别想。

没错。想想父辈，经历的是百废待兴；想想祖辈，经历的是战乱浩劫；而曾祖辈，还生活在积弱难返的晚清呢。他们哪一代人活得不比我们难？可是他们子又生孙，孙又生子，一代一代都挺过来了，我们凭什么不能？

小时候看过一部电视剧，剧名剧情全忘了，只记得一句歌词：

> 要生存，先把泪擦干；走过去，前面是个天。

4

那个中年人走了，如果真是自杀，那是他自己的事。但是，最让人揪心的，是他留下的一双小儿女，由谁来养大成人？两对老父母，谁来养老送终？

中年人的命，不只属于一个人。

再苦再难，只要留得青山在，就不愁没柴烧。不管遭遇何种困境，看得远一点，穿越到未来，回头一看，全部都是过眼云烟。

就让我把本文献给我的朋友们吧，他们大多数上有老、下有小、中间还要还房贷。这里，用电影《乱世佳人》里女主角 Scarlett 的一句台词，作为本文的结尾，与朋友们共勉：

> As God is my witness, as God is my witness they’re not going to lick me. I’m going to live through this and when it’s all over, I’ll never be hungry again. No, nor any of my folk. If I have to lie, steal, cheat or kill. As God is my witness, I’ll never be hungry again. 
>
> 上帝作证，上帝作证，他们休想打垮我。我会度过难关。当一切结束后，我再也不要挨饿。不要，我的家人也不要。即使让我去撒谎，去偷，去骗，去杀人，上帝作证 ，我永远不会再挨饿。
