<map version="1.0.1">
<node TEXT="现代统计图形">
<node TEXT="自序 {#forword .unnumbered}"></node>
<node TEXT="导读 {#guide .unnumbered}"></node>
<node TEXT="案例 {#par:cases .unnumbered}">
<node TEXT="经典图形 {#cha:history}">
<node TEXT="饼图和线图的起源"></node>
<node TEXT="霍乱传染之谜"></node>
<node TEXT="提灯女士的玫瑰图 {#sec:nightingale}"></node>
<node TEXT="拿破仑的俄罗斯远征"></node>
<node TEXT="小结与开始 {#sec:begin}"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="作图工具 {#cha:tools}">
<node TEXT="选择准则"></node>
<node TEXT="R 语言简介 {#sec:R-intro}"></node>
<node TEXT="重现本书图形"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="现代实例 {#cha:data}">
<node TEXT="猪肉价格"></node>
<node TEXT="末日狂奔 {#subsec:canabalt}"></node>
<node TEXT="论坛热度 {#sec:rchive}"></node>
<node TEXT="绝望主妇 {#subsec:tvearn}"></node>
<node TEXT="音乐之声 {#subsec:music}"></node>
<node TEXT="灌篮高手"></node>
<node TEXT="神奇数字 {#subsec:percentage}"></node>
<node TEXT="化点为线 {#subsec:lowess}"></node>
<node TEXT="统计词话 {#subsec:cluster}"></node>
<node TEXT="统计模拟"></node>
<node TEXT="思考与练习"></node></node></node>
<node TEXT="图库 {#par:gallery .unnumbered}">
<node TEXT="单变量图 {#cha:gallery1}">
<node TEXT="条形图/柱状图 {#sec:barplot}"></node>
<node TEXT="Cleveland 点图 {#sec:dotchart}"></node>
<node TEXT="直方图 {#sec:hist}"></node>
<node TEXT="茎叶图"></node>
<node TEXT="箱线图 {#sec:boxplot}"></node>
<node TEXT="小提琴图 {#sec:vioplot}"></node>
<node TEXT="坐标轴须 {#sec:rug}"></node>
<node TEXT="带状图 {#sec:stripchart}"></node>
<node TEXT="饼图 {#sec:pie}"></node>
<node TEXT="QQ 图 {#sec:qqplot}"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="双变量图 {#cha:gallery2}">
<node TEXT="散点图 {#sec:plot-default}"></node>
<node TEXT="一元函数曲线图 {#sec:curve}"></node>
<node TEXT="向日葵散点图 {#sec:sunflowerplot}"></node>
<node TEXT="平滑散点图 {#sec:smoothScatter}"></node>
<node TEXT="风玫瑰图 {#sec:windrose}"></node>
<node TEXT="生存函数图"></node>
<node TEXT="条件密度图 {#sec:cdplot}"></node>
<node TEXT="棘状图 {#sec:spineplot}"></node>
<node TEXT="二维箱线图 {#sec:bagplot}"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="多变量图 {#cha:gallery3}">
<node TEXT="散点图矩阵 {#sec:scatterplot-matrix}"></node>
<node TEXT="条件分割图 {#sec:coplot}"></node>
<node TEXT="符号图 {#sec:symbols}"></node>
<node TEXT="星状图、蛛网图、雷达图 {#sec:stars}"></node>
<node TEXT="脸谱图 {#sec:faces}"></node>
<node TEXT="三元图 {#subsec:ternary}"></node>
<node TEXT="马赛克图 {#sec:mosaicplot}"></node>
<node TEXT="因素效应图 {#plot-design}"></node>
<node TEXT="交互效应图"></node>
<node TEXT="分类与回归树图 {#sec:rpart}"></node>
<node TEXT="平行坐标图 {#sec:parcoords}"></node>
<node TEXT="调和曲线图 {#sec:andrews-curve}"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="矩阵图形 {#cha:gallerymatrix}">
<node TEXT="等高图/等高线 {#sec:contour}"></node>
<node TEXT="颜色等高图/层次图 {#sec:filled-contour}"></node>
<node TEXT="颜色图 {#sec:image}"></node>
<node TEXT="三维透视图 {#sec:persp}"></node>
<node TEXT="矩阵图、矩阵点、矩阵线 {#sec:matplot}"></node>
<node TEXT="热图"></node>
<node TEXT="关联图 {#sec:assocplot}"></node>
<node TEXT="四瓣图 {#sec:fourfoldplot}"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="作图经验 {#chap:principle}">
<node TEXT="图形选择 {#sec:data-type}"></node>
<node TEXT="作图原则"></node>
<node TEXT="统计原则 {#sec:stat-principle}"></node>
<node TEXT="图形总结 {#sec:base-graph-ext}"></node>
<node TEXT="思考与练习"></node></node></node>
<node TEXT="系统 {#par:systems .unnumbered}">
<node TEXT="R 基础作图系统 {#cha:elements}">
<node TEXT="作图函数"></node>
<node TEXT="作图元素"></node>
<node TEXT="页面布局 {#sec:multipage}"></node>
<node TEXT="交互操作 {#sec:interaction}"></node>
<node TEXT="图形设备 {#sec:device}"></node>
<node TEXT="应用示例"></node>
<node TEXT="小结"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="**ggplot2** 系统 {#cha:ggplot2}">
<node TEXT="快速体验"></node>
<node TEXT="基本框架"></node>
<node TEXT="构成元素"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="其它作图系统 {#cha:system}">
<node TEXT="网格图形系统 {#sec:grid-graphics}"></node>
<node TEXT="**lattice** 网格图形 {#sec:lattice}"></node>
<node TEXT="rggobi 动态交互图形 {#sec:dynamic-graphics}"></node>
<node TEXT="plotly 交互图形 {#sec:interactive-graphics}"></node>
<node TEXT="**rgl** 三维图形 {#sec:rgl}"></node>
<node TEXT="动画视频 {#sec:animation}"></node>
<node TEXT="shiny 图形界面 {#cha:GUI}"></node>
<node TEXT="小结"></node>
<node TEXT="思考与练习"></node></node>
<node TEXT="古统新修记 {#postscript .unnumbered}"></node>
<node TEXT="参考文献 {#references .unnumbered}"></node></node>
<node TEXT="附录 {-} ">
<node TEXT="删减章节">
<node TEXT="中美对比 {#subsec:china-vs-us}"></node>
<node TEXT="新冠疫情 {#sec:covid}"></node>
</node></node>
</node></map>
