# 序言

# 前言 

## R的学习困境 

## R是什么  

## 本书如何使用  

## 致谢 

# 初见 

## 结缘：下载安装 

## 第一次畅谈：计算 

## 第一张留影：作图 

## 课外活动：对R的表白

# 数据 

## 输入：读取文件 

## 计算：数据处理和作图 

## 输出：保存文件 

## 课外活动：有R伴我走天涯  

# 作图 

## 控制图像：线型，点状，颜色 

## 丰富内容：直线、网格和图例 

## 多图合一：三种布局 

## 保存图片：pdf，png，jpg 

## 课外活动： R的毛坯房与精装修 

# 拟合 

## 线性拟合：散点图的趋势线 

## 在绘图区添加数学表达式 

## 非线性拟合：一个指数递减模型 

## 课外活动：助理团与自助餐 

# 循环 

## 假如没有循环  

## 循环是个救世主 

## 人口增长模型  

## 制作动画 

## 超越循环 

## 课外活动：信息提示 

# 分支 

## 判断：逻辑运算 

## 选择：如果，那么，否则  

## 课外活动：复活节

# 办公 

## 从Excel到R代码 

## 从Word到R文档 

## 从Powerpoint到R幻灯片 

## 课外活动：用R做网站 

# 习题 

## 向量、矩阵、数据框和列表 

## A卷：照猫画虎题  

## B卷：自由发挥题 

# 函数 

## 内置函数：全自动厨师机 

## 自定义函数：自制厨师机 

## 扩展包：美食王国 

## 课外活动：餐后甜点 

# 字符 

## 狐狸从懒狗身上跳过 

## 千字文的重复字 

## 整理读书笔记

## 课外活动：张无忌的困惑 

# 地图 

## 点阵地图 

## 矢量地图 

## 交互地图 

## 课外活动：动画地图 

# 时间 

## 生日是哪天：时刻的获取 

## 生日星期几：时刻的格式 

## 生日差几天：时刻的计算 

## 时刻的作图 

## 课外活动：夏令时 

# 文件 

## 整理照片 

## 从网页批量下载和整理图片 

## 从大量文件里提取汇总信息 

## 课外活动：打通任督二脉 

# 工作 

## 自动完成业务报表 

## 可重复研究报告

# 写书 

## 魅力不可挡

## 磨刀不误砍柴工 

## 见证奇迹的时刻 

## 写学术论文 

## 写学位论文 

## 生成思维导图 

## 写散文日记 

## 记录吉他谱 

## 课外活动：创建新模板

# 建网 

## 准备工作 

## 用 R blogdown 搭建个人博客 

## 用 R blogdown 搭建科研网站 

## 课外活动：搭建自己的网站 

# 答疑 

## 菜鸟常犯错误和常见问题 

## 习题参考答案 

# 后记

*XMind - Trial Version*