---
title: '世上安得两全法，不负如来不负卿'
author: "赵鹏"
date: '2018-03-09'
slug: monkey-king-3
summary: "然而，细细考察，这两句却并非仓央嘉措的原句。"
tags:
- post
bibliography: [zhaor.bib]
categories: []
---

最近得知电影《西游记 女儿国》的上映。我对剧情完全无感，只对主题歌产生了兴趣：

> 男：
> 
> 世上安得两全法 不负如来不负卿
> 
> 反省凡心损梵行 从来如此莫聪明
> 
> 既生苦难我西行 何生红颜你倾城
> 
> 如何抹去你身影 如同忘却我姓名

> 女：
> 
> 说什么王权富贵 怕什么戒律清规
> 
> 心恋我百转千回 快带我远走高飞
> 
> 念什么善恶慈悲 等什么望穿秋水
> 
> 任来世枯朽成灰 换今生与你相随

歌词乍一看很好，却隐约觉得有些不对劲。

好自不必多言，不对劲在哪里呢？

(1)

歌词的作者，署名是“仓央嘉措/杨洁/赵英俊”。

仓央嘉措是谁呢？西藏六世达赖，生活在清康熙年间，身世传奇，有“情僧”之称。

一位活佛，被称为“情僧”，下场好不了。一边当活佛，一边谈恋爱，除非有济公吃鸡的本事，否则就像唐后主李煜：好诗人，却是个不务正业的糟糕领袖。

仓央嘉措怎么就成了词作者呢？因为歌词里有这么一句，据说是仓央嘉措所作：

> 世上安得两全法 不负如来不负卿

然而，细细考察，这两句却并非仓央嘉措的原句。

原句是什么？

是这样的：

> མཛངས་མའི་ཐུགས་དང་བསྟུན་ན།།
> 
> ཚེ་འདིའི་ཆོས་སྐལ་ཆད་འགྲོ།།
> 
> དབེན་པའི་རི་ཁྲོད་འགྲིམསན།།
> 
> བུ་མོའི་ཐུགས་དང་འགལ་འགྲོ།།



晕了没？我是晕了。是的，原诗用藏语写成。藏学家于道泉（已故）将它直接翻译了过来，就是：

> 若要随彼女的心意
>
> 今生与佛法的缘分断绝了
>
> 若要往空寂的山岭间去云游
>
> 就把彼女的心愿违背了

后来，文学家曾缄（已故）觉得这个翻译丧失了韵味，于是重译为：

> 曾虑多情损梵行，
>
> 入山又恐别倾城。

已经翻译完了，但是感觉好像这诗没说完啊，于是译者加了两句，来深化主题：

> 世间安得双全法，
> 
> 不负如来不负卿。

这样看来，这两句的作者与其说是仓央嘉措，倒不如说是曾缄。

这首歌的男声显然是唐三藏的口吻。唐朝的和尚唱起了清朝和尚、而且是汉传佛教高僧唱起了藏传佛教活佛署名的诗，弄得我有点想参加吐槽大会了。

好在意境上，仓央嘉措的诗句，跟唐僧的两难心境是相当吻合的。

然而，后面的歌词就不对路了。 

> 快带我远走高飞

事实是唐僧要远走高飞，离开女儿国去西天取经，女王不肯离开她的国土和臣民，怎么唱成了女王想远走高飞呢？如果那样的话，不如随唐僧一路西行啊，权当收了个四徒弟。

心里想的是“留下来”，嘴上却说“带我走”，女王就是心口不一。

(2)

到头来，这首歌的点睛之笔，仍然是"王权富贵" 一句， 出自86 版西游记的《女儿情》：

> 鸳鸯双栖蝶双飞， 满园春色惹人醉。
> 
> 悄悄问圣僧， 女儿美不美，女儿美不美。
> 
> 说什么王权富贵， 怕什么戒律清规。
> 
> 只愿天长地久， 与我意中人儿紧相随。
> 
> 爱恋伊，爱恋伊，愿今生常相随。


而这首歌的词作者，就是 86 版西游记的导演杨洁（已故）。

老实说，《西游记 女儿国》若非赵丽颖颜值担当，我是看不下去的。为此，我还重温了一下 86 版西游记的《趣经女儿国》一集，那么影版就更不想看了——朱琳饰演的女王，才是那个美丽、端庄、重情义、识大体的女王啊。

(3)

《女儿情》一曲，世间人皆知，至今仍在传唱。

这首歌还有一首姊妹篇，名叫《相见难 别亦难》，据说是闫肃（已故）作词，恐怕知道的就少了。

> 相见难，别亦难， 怎诉这胸中语万千。
> 
> 我柔情万种，他去志更坚，只怨今生无缘。
> 
> 道不尽声声珍重，默默地祝福平安。
> 
> 人间事常难遂人愿，且看明月又有几回圆。
> 
> 远去矣，远去矣， 从今后梦萦魂牵。

《女儿情》唱于这对璧人畅游御花园之日，《相见难》唱于二人分别之时。虽然是同一曲调，但编曲伴奏全然不同。前者温婉细腻，乐而不淫；后者悲壮凄美，哀而不伤。


如果要吐槽，这里算是个槽点：“相见难别亦难”之句，出自晚唐诗人李商隐，而唐僧生活于初唐；“人间事常难遂人愿”一句，化自宋代苏轼《水调歌头 明月几时有》，略有穿越。

然而，用李商隐的这首诗，来形容彼时女王和唐僧的心境，却比仓央嘉措的诗更为细腻：

> 相见时难别亦难，东风无力百花残。 
> 
> 春蚕到死丝方尽，蜡炬成灰泪始干。 
> 
> 晓镜但愁云鬓改，夜吟应觉月光寒。 
> 
> 蓬山此去无多路，青鸟殷勤为探看。 



“丝方尽”即“思方尽”。《趣经女儿国》一集结尾处是女王目送唐僧远去，望穿秋水依依不舍，不知是不是如春蚕般，到死才了却此番思念？



(4)

86 版西游记里，有那么几集，我小时候，一看见就换台了，《趣经女儿国》就是其中之一。偶尔看一次，全是冲着蝎子精的面子。

长大之后，这一集却不忍心跳过了。

杨洁女士已经驾鹤西去。然而念起这两句，仍然让人心动：

> 悄悄问圣僧，女儿美不美，女儿美不美？
>

我想，若我是圣僧，当时我就从了。

可是，时光倒流，一个女孩也曾拉着我的衣袖，反反复复地问：

> 女儿美不美，女儿美不美？

我心想：这个女生，好烦。